### ISSUE TITLE
Better building names for imports

### ISSUE THREAD

**Issue by bcamper** [polygon-city/building-database#104]
Spinoff from #85: it would be great to come up with a scheme for better names for auto-imported buildings, other than UUID-XXXXXXX :)  Though it would have a high miss and/or error rate, we could consider a reverse geocode against OSM and/or OpenAddresses.

**Comment by robhawkes** [comment]
Definitely – the UUID stuff isn't the best 😄

The buildings already go through some reverse geocode process with Nominatim to get the local area description so we can see what can be pulled from that as a quick fix and auto-populate some name if one hasn't been provided. I'll also move the UUID elsewhere as a private tag as it's useful for batch upload continuation and for future things like versioning.

**Comment by robhawkes** [comment]
So I've had a poke around with Nominatim and we can certainly get some usable address data for at least Berlin – I assume for the other CityGML cities too (they tend to have decent OSM coverage). There are a couple of issues though:

- The coordinates provided by CityGML are relative to the model origin, which isn't the building centroid, so it's possible for this point to lay between 2 buildings and provide the wrong address (eg. a set of terraced houses)
- The addresses are sometimes wrong, especially in cases where a building doesn't exist on OSM – Nomitatim seems to pick a building relatively nearby and use that instead

A lot of this isn't an issue if we're ok not using the house number / building name, though that's arguably the one bit you do want. Otherwise, we can implement a rough-and-ready approach that uses building numbers and accept that some may just be wrong for now (and update them later when we have a more robust approach) – I'm going to pursue this option for now until we think of something better.

**Comment by robhawkes** [comment]
We're getting somewhere – I've got it degrading the name based on various address components (if existing), including the bizarre "address29" property which is possibly the most useful property name in the world.

I've deliberately left out the suburb, city and country data as I feel that would make the names too long and we already have that included on the main building page (as below).

![](http://cl.ly/image/0J2v2c0M2W07/Screen%20Shot%202015-03-26%20at%2012.01.05.png)

**Comment by robhawkes** [comment]
Pushed via 8df8ffc and I've also pushed an update to the KML importer to use this new feature.

**Comment by robhawkes** [comment]
0fabd97e3f46e4c781fbe4a423e03f1c1b612c14 further updates this automated naming to account for situations where no name can be found, or when certain address tags don't exist. Before this fix some buildings would have a blank name, or just a house number and no road.
