### ISSUE TITLE
"Model scale" input behavior

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database#31]
to reproduce:
- upload a model
- on "Set building location" page, adjust the scale

results:
- scale of building is reset unpredictably with the first adjustment, showing a scale of "1" to be some scale other than the initial scale

expected results:
- "model scale" input will function as a multiplier on the initial scale of the model

**Comment by robhawkes** [comment]
Haha, not sure how I missed that one! I suppose I didn't touch the scale on the models it doesn't affect (anything that isn't a collada upload) and because of #9 the incorrect scale wasn't showing itself.

This requires a little bit of thought as I believe only collada models from SketchUp contains a scaling value (related to metres) that we can use to pre-populate this field. Everything else probably needs to assume that the model is at true scale and start with a scaling value of 1.

**Comment by meetar** [comment]
Would we ever want to use any of the models' scaling factors? It might be
better to just start them all at 1, for consistency – but I suppose there
might be a case where that's less useful.

**Comment by robhawkes** [comment]
This is mostly used by SketchUp as it sets a value in the exported collada file as a fraction to apply later on if the model units are in anything other than metres.

Ignoring that and setting the value to 1 could work, though it'd mean the models that do already have a correct scaling value (eg. exports from SketchUp) will need to be re-scaled during the upload process and will likely end up with a value different to the correct one in the model.

I don't think it's too much of a big deal to pre-populate the scale if it exists in the uploaded collada file, otherwise we fall back to a value of 1 (thus assuming model units are 1:1 with metres).

**Comment by robhawkes** [comment]
04e01b023b42078d41fe30ad90a36bd032889c9b and c1ba701 introduce fixes to solve this for now until something more robust is worked out. The initial scale is calculated from the model now and when mouse-scrolling within the scale input the scale value change is more refined.

**Comment by robhawkes** [comment]
This has been in for a while now and seems to work ok. I'm going to close the issue and we can revisit it in the future should the fix need refining.
