### ISSUE TITLE
Check z-height of uploads

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database#51]
![screen shot 2015-01-29 at 5 25 31 pm](https://cloud.githubusercontent.com/assets/459970/5967582/6666e97a-a7dc-11e4-9057-4a323ce3abf4.png)

Not sure how we'd do this short of going through all the vertices, but if there's some way to find the min z we could offer to move the model to the groundplane if it's not there already

**Comment by robhawkes** [comment]
Haha, wow that's not good! I'm wondering if this is something we should only apply in the ViziCities viewer rather than by manipulating the raw model file (so the view looks ok but the downloads are left as-is).

I'll have a look at some of the options, it shouldn't be too hard to loop through all the vertices and find the minZ. It's possible we can use some of the Three.js helper methods for finding bounding boxes and stuff.

**Comment by bcamper** [comment]
Hmm, this seems like a case where it might actually make sense to modify the model vertices we store in this case, otherwise all rendering clients would have to account for this?

**Comment by robhawkes** [comment]
It depends if we want to enforce a particular requirement that all models uploaded are positioned relative to the ground plane. It sounds normal but from my experience a few of the 3D city model creators like creating their models with a z-offset relative to the terrain. I personally find it confusing and it wouldn't actually matter if we reposition them so z=0 as the whole underside of the building won't be flat anyway.

I imagine this is an exception rather than the rule so I'll look into the options we have. It's a lot easier to only do this in the ViziCities view as otherwise we'll need to way to reach into all the various 3D file-formats to modify the correct vertices.

Are there any buildings that may need to be legitimately offset from the ground?

**Comment by meetar** [comment]
I presume you mean models with z-values varying depending on local terrain, and not models with altitude-based offsets. We'll certainly run into the terrain issue eventually, especially given that the buildings will be used in contexts with 3D terrain. I'm not sure if there's a standard for this, but I'd imagine at the very least we'd want to store some kind of centroid-based z-offset value, maybe a ground-plane value, so that the building's centroid (or whatever point is being used to set "location") is correctly positioned in z-space but doesn't look completely wrong when shown on a flat surface, as will inevitably happen.

(To do this properly we'll have to integrate terrain into the building-positioning step, but I don't think we need to do that for launch.)

Below are a couple of extreme examples which illustrate the problem: the OHSU hospital complex in Portland OR and the Getty Museum in LA. In each example, if you take the whole complex to be a single object with a geo-referenced location (whether it's the centroid or not), we have no guarantee that the object's coordinate system is set so that its z-axis origin begins at the ground level.

Programmatic approaches seem fraught, for various reasons. Allow the user to set an offset at upload is one way to solve this, but until we integrate 3D terrain will mostly solve the problem of display on flat ground.

![screen shot 2015-02-02 at 11 06 07 am](https://cloud.githubusercontent.com/assets/459970/6004871/102962fe-aad4-11e4-8b68-476a0136dded.png)

![screen shot 2015-02-02 at 11 08 30 am](https://cloud.githubusercontent.com/assets/459970/6004872/14bdbbf8-aad4-11e4-8eae-0e482d4baa9e.png)

**Comment by robhawkes** [comment]
I was actually talking about this with someone from CyberCity3D the other day about how frustrating it is because it means that, unless you have the identical terrain, you'll always have a gap underneath the building.

I wonder how this was tackled with Google Earth; I'm assuming some buildings were just allowed to have a z-offset. It seems that way from the [KML model definition](https://developers.google.com/kml/documentation/kmlreference#model) too – it uses `clampToGround` to override a given altitude value to place the model at (which implies the raw model is placed at z=0, or at least some fixed z origin).

Is it not simpler to just require buildings being based on a z=0 origin, as a guideline? Rather than build in some automated processing that we'd have to adapt for every different file-format we want to support. eg. Do we envisage this being a regular occurrence?

**Comment by bcamper** [comment]
Yeah I see why it's a mess. I'm fine with initially assuming/requiring models be based at z=0, and then just waiting and seeing if it's a problem in practice -- if that is OK with you guys.

**Comment by robhawkes** [comment]
That sounds good to me, it can become part of #53 (eg. an FAQ, or a guideline in the upload process).

**Comment by meetar** [comment]
Added to the guidelines – archiving this for now.
