### ISSUE TITLE
Add smtp info to config file

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database#71]
Get sendmail working from the local build using any handy account, then swap that out once we get the chef vm up and running.

**Comment by robhawkes** [comment]
This is easy enough to add in, it's just a case of swapping out the stock email handler (directly via Node) to an SMTP handler with external config options. It does mean that we're hardwired for SMTP though – assuming that's the transport we want to use (rather than an API-led approach with something like Mandrill, Postmark or Mailgun).

Regardless, I'll add in SMTP support now as it's most flexible and we can change the transport to whatever you guys use already for other things if different.

**Comment by robhawkes** [comment]
This has landed with 93dd769, meaning that emails won't be sent unless you set up SMTP options in `/config/config.js` (look at the sample config). You can add further SMTP options as per [the ones available here](https://github.com/andris9/nodemailer-smtp-transport#usage).

Also, I found [FakeSMTP](https://nilhcem.github.io/FakeSMTP/) to be really useful for testing this locally.
