### ISSUE TITLE
Olympic Stadium is not selectable in "link to OSM" page

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database#74]
To reproduce:
- add a building
- set its location to 51.53889, -0.016425

Result:
- on the "link to openstreetmap" page, the Olympic Stadium is not a selectable structure

![screen shot 2015-02-19 at 12 25 12 pm](https://cloud.githubusercontent.com/assets/459970/6271979/7b1a2bdc-b832-11e4-9d62-c98a505825c2.png)

Expected result:
- the stadium will have a blue outline and be selectable

Notes: 
Olympic Stadium: http://www.openstreetmap.org/relation/2307069
tags:
> building: stadium
> stadium: building
> type:	multipolygon

**Comment by robhawkes** [comment]
Ok, so this isn't displaying because the building tag is on the relation and not the way for the actual stadium – the joys of not having a strict system for tagging in OSM.

There are 2 take-aways from this that we should look at:

1. How should relations be displayed on the OSM map?
2. Should ways with tag `leisure=stadium` (like this one) be considered buildings?

Number 2 is straightforward, though the relations question is harder. Adding the relations and their ways to the map is easy, but do we want to attach the building model to the relation ID or the ID of the way that has been clicked on? Or both? Also, do we want to display all the ways of the relation or some filtered selection? In this example, none of the ways have a building tag so it's possible to clutter the map with tonnes of unrelated polygons (potentially preventing you from clicking on the one you want because so many are on top of it).

I don't actually know right now if we can work out the relation ID of a clicked way using Overpass as the connection is defined on the relation (which has no polygon to click) and not on the way. This might put a spanner in the works. Also, if we decide to use the clicked way ID and not the relation, then obviously that may be kind of pointless as the way doesn't have a building tag on it, even though it may be the building.

What do you think?

**Comment by bcamper** [comment]
To document, our conclusion for now:

- Add relations with a building tag to the Overpass query
- Allow buildings to be attached to a relation id
- Whenever any way/node that is part of the relation is selected, associate the building with the relation id (rather than the actual clicked way id, which may just be a piece of a building, such as an inner polygon ring)

**Comment by robhawkes** [comment]
Oh the bizarre world of OSM tags – I've managed to get the relations in (not pushed yet) but I think we're going to need to tweak things a bit as the tags used for this stadium are weird. There's actually 3 relations that the stadium outline is attached to; 1 is the building and 2 are defined as `building=roof`. I've set `building=roof` as an exclusion in our Overpass query for now.

**Comment by robhawkes** [comment]
0e51ed0 will link a building to an OSM relation if the clicked way does not have a building tag but does have a relation with a building tag.

**Comment by bcamper** [comment]
Hm yeah, `building=roof` is not a typical building tag as far as I know. But of course there is no set of officially accepted tags, so it will be hard to police this kind of thing (not unique to this project, most OSM software is full of these exceptions :)  This does remind me though, it *is* valid to have multiple relations for the way, like for `multipolygon`. But it sounds like the ambiguity here was around multiple `building` tag relations, is that right?

**Comment by robhawkes** [comment]
The way I've implemented it will take the first relation with a building tag for the (non-building) way. We may need to tweak this in the future but it seemed to work and it's nice and simple. I'm not sure what you mean about the ambiguity around multiple building tag relations though.

**Comment by bcamper** [comment]
Ah sorry, yeah I was referring to what you mentioned -- cases where the way might belong to multiple `building` relations, and there is no clear way to disambiguate and choose one. Hopefully this is rare and your solution sounds like a good start. Good to close this on my end.
