### ISSUE TITLE
Crash on signup: ECONNREFUSED

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database#79]
To reproduce:
- navigate to /signup
- enter user, password, and email
- submit form

Result:
- app crashes - browser console output:

`GET http://localhost:3000/signup net::ERR_CONNECTION_REFUSED`
- node output:
```
Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by robhawkes** [comment]
Ah, this seems to be caused by the upgrade to an SMTP-only system (as per #71) and the fact the system can't send an email because it can't find an SMTP server. The error message should be a bit more constructive though – I'll change that. In the meantime, I'd suggest setting up a local SMTP server using the FakeSMTP app in #71, add those details to the config and away you go.

**Comment by robhawkes** [comment]
d8ac632 improves the SMTP error message

**Comment by meetar** [comment]
I've started FakeSMTP using port 2555 (it wouldn't let me use 25, said it might be busy?) and changed that port in my config file, but on signup I get a 502 "bad gateway" error, with no messages in the app console or the FakeSMTP "SMTP log" window.

**Comment by meetar** [comment]
Got it – user error: had multiple copies of the server running, and was accessing the wrong one. Good morning! :coffee:
